// Module6_Frontend(Baskar M)/handson_5/student-portal-react/src/components/CourseCard.jsx
function CourseCard({
  id,
  name,
  code,
  credits,
  grade,
  onEnroll
}) {
  return (
    <div className="card">
      <h3>{name}</h3>

      <p>{code}</p>

      <p>Credits : {credits}</p>

      <p>Grade : {grade}</p>

      <button
        onClick={() =>
          onEnroll({
            id,
            name
          })
        }
      >
        Enroll
      </button>
    </div>
  );
}

export default CourseCard;

// Module6_Frontend(Baskar M)/handson_8/student-portal-vue/src/components/CourseCard.vue
<template>
  <div class="course-card">
    <h3>{{ name }}</h3>
    <p><strong>Code:</strong> {{ code }}</p>
    <p><strong>Credits:</strong> {{ credits }}</p>
    <p><strong>Grade:</strong> {{ grade }}</p>
  </div>
</template>

<script setup>
defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String
})
</script>

<style scoped>
.course-card {
  border: 1px solid #ccc;
  border-radius: 8px;
  padding: 15px;
  margin: 10px;
}
</style>
